name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        shell: pwsh
        run: dotnet restore .\FileIntakeAssistant.sln --configfile .\NuGet.config

      - name: Build
        shell: pwsh
        run: dotnet build .\FileIntakeAssistant.sln --no-restore

      - name: Test
        shell: pwsh
        run: dotnet test .\FileIntakeAssistant.sln --no-build --verbosity normal
